name: 'Build Ionic React'
description: 'Build Ionic React'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./packages/core
        filename: CoreBuild.zip
    - name: Install React Dependencies
      run: pnpm install
      shell: bash
      working-directory: ./packages/react
    - name: Lint
      run: pnpm run lint
      shell: bash
      working-directory: ./packages/react
    - name: Build
      run: pnpm run build
      shell: bash
      working-directory: ./packages/react
    - name: Test Spec
      run: pnpm run test.spec
      shell: bash
      working-directory: ./packages/react
    - name: Check Diff
      run: git diff --exit-code
      shell: bash
      working-directory: ./packages/react
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-react
        output: packages/react/ReactBuild.zip
        paths: packages/react/dist packages/react/css
