name: 'Build Ionic Vue'
description: 'Build Ionic Vue'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./packages/core
        filename: CoreBuild.zip
    - name: Install Vue Dependencies
      run: pnpm install
      shell: bash
      working-directory: ./packages/vue
    - name: Lint
      run: pnpm run lint
      shell: bash
      working-directory: ./packages/vue
    - name: Build
      run: pnpm run build
      shell: bash
      working-directory: ./packages/vue
    - name: Check Diff
      run: git diff --exit-code
      shell: bash
      working-directory: ./packages/vue
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-vue
        output: packages/vue/VueBuild.zip
        paths: packages/vue/dist packages/vue/css
