packages:
  - "core"
  - "docs"
  - "packages/angular"
  - "packages/angular-server"
  - "packages/angular-schematics"
  - "packages/vue"
  - "packages/vue-router"
  - "packages/react"
  - "packages/react-router"
