name: 'Test React E2E'
description: 'Test React E2E'
inputs:
  app:
    description: 'The specific test application'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./packages/core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react
        path: ./packages/react
        filename: ReactBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-react-router
        path: ./packages/react-router
        filename: ReactRouterBuild.zip
    - name: Create Test App
      run: ./build.sh ${{ inputs.app }}
      shell: bash
      working-directory: ./test-apps/react
    - name: Install Dependencies
      run: pnpm install
      shell: bash
      working-directory: ./test-apps/react/build/${{ inputs.app }}
    - name: Build
      run: pnpm run build
      shell: bash
      working-directory: ./test-apps/react/build/${{ inputs.app }}
    - name: Run Tests
      run: pnpm run e2e
      shell: bash
      working-directory: ./test-apps/react/build/${{ inputs.app }}

