name: 🐛 Bug Report
description: Create a report to help us improve Ionic Framework
title: 'bug: '

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please ensure you have completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
          required: true
        - label: I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
          required: true
        - label: I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.
          required: true

  - type: dropdown
    id: affected-versions
    attributes:
      label: Ionic Framework Version
      description: Which version(s) of Ionic Framework does this issue impact? For Ionic Framework 1.x issues, please use https://github.com/ionic-team/ionic-v1. For Ionic Framework 2.x and 3.x issues, please use https://github.com/ionic-team/ionic-v3.
      options:
        - v4.x
        - v5.x
        - v6.x
        - v7.x
        - Nightly
      multiple: true
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please explain the steps required to duplicate this issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Code Reproduction URL
      description: Please create a minimal reproduction of the issue. The minimial reproduction should include only the code required to reproduce the issue. Try out our [Getting Started Wizard](https://ionicframework.com/start#basics) to quickly spin up an Ionic Framework starter app. Alternatively, try forking one of the [component playgrounds](https://ionicframework.com/docs/components). Issues without a code reproduction URL may be closed by the Ionic Team.
      placeholder: https://github.com/...
    validations:
      required: true

  - type: textarea
    id: ionic-info
    attributes:
      label: Ionic Info
      description: Please run `ionic info` from within your Ionic Framework project directory and paste the output below.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc.
