name: 'Build Ionic Vue Router'
description: 'Builds Ionic Vue Router'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./packages/core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-vue
        path: ./packages/vue
        filename: VueBuild.zip
    - name: Install Vue Router Dependencies
      run: pnpm install
      shell: bash
      working-directory: ./packages/vue-router
    - name: Lint
      run: pnpm run lint
      shell: bash
      working-directory: ./packages/vue-router
    - name: Build
      run: pnpm run build
      shell: bash
      working-directory: ./packages/vue-router
    - name: Test Spec
      run: pnpm run test.spec
      shell: bash
      working-directory: ./packages/vue-router
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-vue-router
        output: ./packages/vue-router/VueRouterBuild.zip
        paths: packages/vue-router/dist
