name: 'Build Ionic Angular'
description: 'Build Ionic Angular'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip
    - name: Install Angular Dependencies
      run: pnpm install
      shell: bash
      working-directory: ./packages/angular
    - name: Lint
      run: pnpm run lint
      shell: bash
      working-directory: ./packages/angular
    - name: Build
      run: pnpm run build
      shell: bash
      working-directory: ./packages/angular
    - name: Check Diff
      run: git diff --exit-code
      shell: bash
      working-directory: ./packages/angular
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-angular
        output: ./packages/angular/AngularBuild.zip
        paths: ./packages/angular/dist
