name: 'Test Core Spec'
description: 'Test Core Spec'
inputs:
  stencil-version:
    description: 'The NPM tag of @stencil/core to install.'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install Dependencies
      run: pnpm install
      working-directory: ./packages/core
      shell: bash
    - name: Install Stencil ${{ inputs.stencil-version }}
      run: pnpm install @stencil/core@${{ inputs.stencil-version }}
      shell: bash
      working-directory: ./packages/core
      if: ${{ inputs.stencil-version != '' }}
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./packages/core
        filename: CoreBuild.zip
    - name: Test
      run: pnpm run test.spec --ci
      shell: bash
      working-directory: ./packages/core
