name: 'Build Ionic Core'
description: 'Build Ionic Core'
inputs:
  ionicons-version:
    description: 'The NPM tag of ionicons to install.'
    type: string
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install Dependencies
      run: pnpm install
      working-directory: ./packages/core
      shell: bash
    # If an Ionicons version was specified install that.
    # Otherwise just use the version defined in the package.json.
    - name: Install Ionicons Version
      if: inputs.ionicons-version != ''
      run: pnpm install ionicons@${{ inputs.ionicons-version }}
      working-directory: ./packages/core
      shell: bash
    - name: Build Core
      run: pnpm run build --ci
      working-directory: ./packages/core
      shell: bash
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-core
        output: packages/core/CoreBuild.zip
        paths: packages/core/dist packages/core/components packages/core/css packages/core/hydrate packages/core/loader packages/core/src/components.d.ts packages/core/api.txt
