name: 'Build Ionic Core with Stencil Prerelease'
description: 'Build Ionic Core with a Prerelease Build of Stencil'
inputs:
  stencil-version:
    description: 'The NPM tag of @stencil/core to install.'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install Dependencies
      run: pnpm install
      working-directory: ./packages/core
      shell: bash
    - name: Install Stencil ${{ inputs.stencil-version }}
      working-directory: ./packages/core
      run: pnpm i @stencil/core@${{ inputs.stencil-version }}
      shell: bash
    - name: Build Core
      run: pnpm npm run build -- --ci --debug --verbose
      working-directory: ./packages/core
      shell: bash
    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: ionic-core
        output: packages/packages/core/CoreBuild.zip
        paths: packages/core/dist packages/core/components packages/core/css packages/core/hydrate packages/core/loader packages/core/src/components.d.ts
